"""add campaign stop conditions

Revision ID: 80defc32a0c5
Revises: 
Create Date: 2026-05-03 15:37:22.058861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '80defc32a0c5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_powermta_replies_id'), table_name='powermta_replies')
    op.drop_table('powermta_replies')
    op.add_column('campaigns', sa.Column('max_bounces', sa.Integer(), nullable=True))
    op.add_column('campaigns', sa.Column('max_complaints', sa.Integer(), nullable=True))
    op.add_column('campaigns', sa.Column('max_unsubscribes', sa.Integer(), nullable=True))
    op.add_column('campaigns', sa.Column('stopped_by_condition', sa.Boolean(), nullable=False))
    op.add_column('campaigns', sa.Column('stop_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'stop_reason')
    op.drop_column('campaigns', 'stopped_by_condition')
    op.drop_column('campaigns', 'max_unsubscribes')
    op.drop_column('campaigns', 'max_complaints')
    op.drop_column('campaigns', 'max_bounces')
    op.create_table('powermta_replies',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('campaign_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('contact_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('step_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('from_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('to_address', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('subject', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('body_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('raw_headers', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('processed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('received_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('powermta_replies_pkey'))
    )
    op.create_index(op.f('ix_powermta_replies_id'), 'powermta_replies', ['id'], unique=False)
    # ### end Alembic commands ###
